FROM jupyter/tensorflow-notebook:tensorflow-2.11.1
LABEL maintainer="Muhammad Mohsin Aslam"
LABEL email="m.mohsin.aslam@gmail.com"
LABEL version="1.0"

RUN pip install tfx==1.14.0
RUN pip install boto3==1.34.61
RUN pip install mlflow==2.11.1